# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_epc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 190)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico_file/sourcefile/title.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QLabel{\n"
"    color: rgb(0, 0, 127);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QComboBox{\n"
"    font: 14pt \"Microsoft Sans Serif\";\n"
"}\n"
"QLineEdit{\n"
"font: 11pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableView{\n"
"    border-color: rgb(0, 85, 0);\n"
"    \n"
"    alternate-background-color: rgb(230, 201, 255);\n"
"    background-color: rgb(199, 205, 255);\n"
"/*    selection-background-color: rgb(85, 255, 0);*/\n"
"\n"
"}\n"
"QPushButton{\n"
"    /*background-color: rgb(170, 255, 127);*/\n"
"    \n"
"    font: 16pt \"Microsoft Sans Serif\";\n"
"    \n"
"    background-color: rgb(239, 239, 119);\n"
"}\n"
"QCheckBox{\n"
"font: 12pt \"Microsoft Sans Serif\";\n"
"    color: rgb(255, 85, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Version = QtWidgets.QLabel(self.centralwidget)
        self.label_Version.setObjectName("label_Version")
        self.horizontalLayout.addWidget(self.label_Version)
        self.comboBox_Version = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Version.setObjectName("comboBox_Version")
        self.comboBox_Version.addItem("")
        self.comboBox_Version.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_Version)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_encoding = QtWidgets.QLabel(self.centralwidget)
        self.label_encoding.setObjectName("label_encoding")
        self.horizontalLayout_2.addWidget(self.label_encoding)
        self.comboBox_encoding = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_encoding.setObjectName("comboBox_encoding")
        self.comboBox_encoding.addItem("")
        self.comboBox_encoding.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_encoding)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Open_Data = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Open_Data.sizePolicy().hasHeightForWidth())
        self.pushButton_Open_Data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Open_Data.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/ITProg02/.designer/backup/sourcefile/open2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Open_Data.setIcon(icon1)
        self.pushButton_Open_Data.setObjectName("pushButton_Open_Data")
        self.horizontalLayout_4.addWidget(self.pushButton_Open_Data)
        self.label_file_path = QtWidgets.QLabel(self.centralwidget)
        self.label_file_path.setObjectName("label_file_path")
        self.horizontalLayout_4.addWidget(self.label_file_path)
        self.pushButton_Process = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Process.sizePolicy().hasHeightForWidth())
        self.pushButton_Process.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Process.setFont(font)
        self.pushButton_Process.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_Process.setIcon(icon1)
        self.pushButton_Process.setObjectName("pushButton_Process")
        self.horizontalLayout_4.addWidget(self.pushButton_Process)
        self.label1_check = QtWidgets.QLabel(self.centralwidget)
        self.label1_check.setStyleSheet("")
        self.label1_check.setObjectName("label1_check")
        self.horizontalLayout_4.addWidget(self.label1_check)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 8)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.menu.setFont(font)
        self.menu.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menu.setToolTip("")
        self.menu.setWhatsThis("")
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_Version.setCurrentIndex(0)
        self.comboBox_encoding.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EPC QR Code Generator"))
        self.label_Version.setText(_translate("MainWindow", "Version:"))
        self.comboBox_Version.setItemText(0, _translate("MainWindow", "001"))
        self.comboBox_Version.setItemText(1, _translate("MainWindow", "002"))
        self.label_encoding.setText(_translate("MainWindow", "Character set"))
        self.comboBox_encoding.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_encoding.setItemText(1, _translate("MainWindow", "1"))
        self.pushButton_Open_Data.setText(_translate("MainWindow", "打開資料"))
        self.label_file_path.setText(_translate("MainWindow", "文件"))
        self.pushButton_Process.setText(_translate("MainWindow", "處理"))
        self.label1_check.setText(_translate("MainWindow", "................."))
        self.menu.setTitle(_translate("MainWindow", "功能選項"))
        self.menu_2.setTitle(_translate("MainWindow", "系統"))
        self.actiona.setText(_translate("MainWindow", "設置打開文件路徑"))
import resourcefile_rc
